React2 week1 homework
YF91925352/meal-share pull request #6
Opened 2023-03-21 17:55 UTC by YF91925352

2023-03-23 22:41 UTC, shpomp requested changes
Nice! 👍🏽 
Some structural and logical changes, but some of the basics are very good! ⭐

2023-03-23 22:41 UTC, shpomp commented on src/client/App.js
> +      <Route exact path="/mealcard">
Good to practise, but you will not use this, as you will need a rout with a path parameter 👍🏽

2023-03-23 22:41 UTC, shpomp commented on src/client/components/MealProvider.jsx
> +  const [list, setList] = useState([]);
A more descriptive name would be better 👌🏽

2023-03-23 22:41 UTC, shpomp commented on src/client/components/Mealist.jsx
> +export default function Mealist() {
camelCase for naming ⚠️

2023-03-23 22:41 UTC, shpomp commented on src/client/components/Mealcard.jsx
> +        {list.map((item) => (
If this is the single meal card, why is it mapping over all the meals, which is already done in MealList?

2023-04-04 12:51 UTC, merged

2023-04-08 10:33 UTC, YF91925352 commented on src/client/components/Mealcard.jsx
> +        {list.map((item) => (
Thx for your review!I will update them!